server:
    port: 8081
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: tiger
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/test_db
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true