server:
    port: 8081
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: tiger
        url: jdbc:mysql://localhost:3306/springboot
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update